version: '3.8'
services:
  web-client:
    build: .
    container_name: web_client_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true